# Numpy

Numpy is the fundamental package for scientific computing with python.<br>
*   It is also called as Numerical Python.<br>
*   Easy and efficient.<br>
*   NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays

In [0]:
import numpy as np

In [5]:
# Creating an array using python.
x = np.array([1,2,3])
print(x)

# Display type of X
print(type(x))

# Display length of x
print(len(x))

[1 2 3]
<class 'numpy.ndarray'>
3


**Create a list and convert it to a numpy array.**

In [7]:
mylist = [1, 2, 3]
x = np.array(mylist)
print(x)

[1 2 3]


In [8]:
# Or Just pass a list.
y = np.array([4, 5, 6])
y

array([4, 5, 6])

 **Creating a Multidimensional array.**

In [10]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

## Functions 

**1. Use the shape method to find the dimensions of the array. (rows, columns)**

In [11]:
print(np.shape(m))

(2, 3)


In [12]:
x= np.array([[1,2,3], [4,5,6], [8,9,10]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [13]:
x.shape

(3, 3)


**2. `arange` returns evenly spaced values within a given interval.**
np.arange(start,stop,step)

In [14]:
n = np.arange(0, 12, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10])

In [15]:
 k=np.arange(3,21,3)
 k

array([ 3,  6,  9, 12, 15, 18])

**3.`reshape` returns an array with the same data with a new shape.**

In [17]:
p = np. array([1,2,3,4,5,6,7,8,9])
p=p.reshape(3,3)
p
              

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n = n.reshape(2,3) # reshape array to be 3x5
n

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [20]:
t= k.reshape(2,3)
t

array([[ 3,  6,  9],
       [12, 15, 18]])

**4. `linspace` returns evenly spaced numbers over a specified interval.**

In [22]:
arr = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
print(arr)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [26]:
a= np.linspace(0,8,15)
a

array([0.        , 0.57142857, 1.14285714, 1.71428571, 2.28571429,
       2.85714286, 3.42857143, 4.        , 4.57142857, 5.14285714,
       5.71428571, 6.28571429, 6.85714286, 7.42857143, 8.        ])

**5. `resize` changes the shape and size of array in-place.**

In [28]:
arr.resize(3, 3)
arr

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [30]:
a.resize(5,3)
a

array([[0.        , 0.57142857, 1.14285714],
       [1.71428571, 2.28571429, 2.85714286],
       [3.42857143, 4.        , 4.57142857],
       [5.14285714, 5.71428571, 6.28571429],
       [6.85714286, 7.42857143, 8.        ]])

**6. `ones` returns a new array of given shape and type, filled with ones.**

In [33]:
arr = np.ones((3, 2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [34]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

**7.`zeros` returns a new array of given shape and type, filled with zeros.**

In [0]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

**8. `eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.**

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**9. `diag` extracts a diagonal or constructs a diagonal array.**

In [36]:
np.diag([[1,2,3], [4,5,6]])

array([1, 5])

**10. Create an array using repeating list (or see `np.tile`)**

In [0]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

**11. Repeat elements of an array using `repeat`.**

In [37]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

## Combining Arrays

In [38]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

**1. Use `vstack` to stack arrays in sequence vertically (row wise).**

In [39]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

**2. Use `hstack` to stack arrays in sequence horizontally (column wise).**

In [40]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

**Basic math operations on numpy array/matrix/vectors**

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [47]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,2,4],[1,3,5]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[2 2 4]
 [1 3 5]]


In [44]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[[ 1  4  7]
 [ 5  8 11]]
[[ 1  0 -1]
 [ 3  2  1]]


In [48]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[[ 2  4 12]
 [ 4 15 30]]
[[0.5        1.         0.75      ]
 [4.         1.66666667 1.2       ]]


In [49]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[[ 1  4  9]
 [16 25 36]]


##  Numpy Math Functions

In [55]:
# Element wise operations.
x = np.array([[0,2,4], [1,3,5]])
y = np.array([[2,4,8], [1,6,10]])
print("Addtion")
print(np.add(x,y))

print('Subtarction')
print(np.subtract(x,y))

print('Multiplication')
print(np.multiply(x,y))

print('Division')
print(np.divide(x,y))


Addtion
[[ 2  6 12]
 [ 2  9 15]]
Subtarction
[[-2 -2 -4]
 [ 0 -3 -5]]
Multiplication
[[ 0  8 32]
 [ 1 18 50]]
Division
[[0.  0.5 0.5]
 [1.  0.5 0.5]]


**Matrix multiplication**

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [0]:
x = np.array([[2,4],[1,3]])
y = np.array([[2,3],[1,2]])

In [63]:
print(np.dot(x,y)) # dot product  1*4 + 2*5 + 3*6

[[ 8 14]
 [ 5  9]]


In [0]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array


**Let's look at transposing arrays. Transposing permutes the dimensions of the array.**

In [64]:
z = np.array([y, y**2])
z

array([[[2, 3],
        [1, 2]],

       [[4, 9],
        [1, 4]]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [65]:
z.shape

(2, 2, 2)

<br>
Use `.T` to get the transpose.

In [67]:
z.T

array([[[2, 4],
        [1, 1]],

       [[3, 9],
        [2, 4]]])

<br>
The number of rows has swapped with the number of columns.

In [66]:
z.T.shape

(2, 2, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [68]:
z.dtype

dtype('int64')

**Use `.astype` to cast to a specific type.**

In [0]:
z = z.astype('f')
z.dtype

**Numpy has many built in math functions that can be performed on arrays.**

In [0]:
a = np.array([-4, -2, 1, 3, 5])

In [111]:
np.sum(a)   # Print sum of all the elements of the array.

3

In [114]:
print(a.max())
print(np.max(a))# Print the maximum element of the array.

5
5


In [72]:
a.min()  # Print the minimum elements of the array.

-4

### Statistics, logarithm, exponetial functions

In [0]:
x = np.array([1,2,3,4,5,6,7,8])

In [109]:
np.mean(x) # Print the average of an elements of the array.

4.5

In [116]:
np.median(x)

4.5

In [115]:
np.mode(x)

AttributeError: ignored

In [117]:
np.std(x)

2.29128784747792

In [118]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154])

In [119]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03])

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [77]:
a.argmax()

4

In [76]:
a.argmin()

0

## Indexing / Slicing

In [79]:
k= np.arange(10)
k.resize(2,5)
k

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [80]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [82]:
# Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.
s[0], s[4], s[-1]

(0, 16, 144)

**Use `:` to indicate a range. `array[start:stop]`**


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [0]:
s[1:5]

array([ 1,  4,  9, 16])

<br>
Use negatives to count from the back.

In [83]:
s[-4:]

array([ 81, 100, 121, 144])

**A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`**

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [0]:
s[-5::-2]

array([64, 36, 16,  4,  0])

<br>
Let's look at a multidimensional array.

In [84]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [87]:
# Use bracket notation to slice: `array[row, column]`

r[2, 2]

14

In [89]:
# use : to select a range of rows or columns
r[3, 3:6]

array([21, 22, 23])

In [90]:
# Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [91]:
# This is a slice of the last row, and only every other element.
r[-1, ::2]

array([30, 32, 34])

**We can also perform conditional indexing.** <br>Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [92]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [93]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Copying Data

**Be careful with copying and modifying arrays in NumPy!**


`r2` is a slice of `r`

In [94]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [95]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [96]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**To avoid this, use `r.copy` to create a copy that will not affect the original array**

In [97]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

**Now when r_copy is modified, r will not be changed.**

In [98]:
r_copy[:] = 10
print(r_copy, '/n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] /n
[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


## Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [99]:
test = np.random.randint(0, 10, (4,3))
test

array([[1, 1, 4],
       [1, 7, 9],
       [3, 5, 7],
       [1, 8, 4]])

**Iterate by row:**

In [100]:
for row in test:
    print(row)

[1 1 4]
[1 7 9]
[3 5 7]
[1 8 4]


* **Iterate by index:**

In [101]:
for i in range(len(test)):
    print(test[i])

[1 1 4]
[1 7 9]
[3 5 7]
[1 8 4]


**Iterate by row and index:**

In [102]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [1 1 4]
row 1 is [1 7 9]
row 2 is [3 5 7]
row 3 is [1 8 4]


 **Use `zip` to iterate over multiple iterables.**

In [103]:
test2 = test**2
test2

array([[ 1,  1, 16],
       [ 1, 49, 81],
       [ 9, 25, 49],
       [ 1, 64, 16]])

In [104]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[1 1 4] + [ 1  1 16] = [ 2  2 20]
[1 7 9] + [ 1 49 81] = [ 2 56 90]
[3 5 7] + [ 9 25 49] = [12 30 56]
[1 8 4] + [ 1 64 16] = [ 2 72 20]
